name: bakan
version: 1.0.0+1
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker:
  pdf: ^3.11.3
  path_provider: ^2.1.3
  open_file: ^3.3.2
  intl:
  fl_chart: 0.60.0 
  cupertino_icons: ^1.0.2
  flutter_native_splash: 
  flutter_local_notifications: ^18.0.1
  android_alarm_manager_plus: ^3.0.2
  device_calendar: 
  table_calendar: ^3.1.3
  flutter_colorpicker: ^1.1.0
  liquid_swipe: ^3.1.0
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1
  share_plus: ^7.2.2
  printing: ^5.12.0
  workmanager:

  googleapis: ^11.4.0
  googleapis_auth: ^1.4.0
  google_sign_in: ^6.1.5
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: 
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/log.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png

    - assets/images/sf/1.png
    - assets/images/sf/2.png
    - assets/images/sf/3.png
    - assets/images/sf/4.png
    - assets/images/sf/5.png
    - assets/images/sf/6.png
    - assets/images/sf/7.png
    - assets/images/sf/8.png
    - assets/images/sf/9.png
    - assets/images/sf/10.png
    - assets/images/sf/11.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/3.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/3.png"
    background_color: "#FFFFFFFF"
    theme_color: "#FFFFFFFF"
  windows:
    generate: true
    image_path: "assets/images/3.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/3.png"

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#eeeeee"
  image: assets/images/sf/1.png
  branding: assets/images/sf/1.png
  color_dark: "#eeeeee"
  image_dark: assets/images/sf/1.png
  branding_dark: assets/images/sf/1.png

  android_12:
    image: assets/images/sf/1.png
    icon_background_color: "#eeeeee"
    image_dark: assets/images/sf/1.png
    icon_background_color_dark: "#eeeeee"

  web: false
